# -*- coding: utf-8 -*-
"""
Gold-standard CRIME-Q assessment of all 20 music studies.
Each entry: study_id -> { item_id: (SCORE, JUSTIFICATION, VERBATIM) }
SCORE in {Yes, No, Partly, Unclear, NA}. VERBATIM is an exact quote + location,
or "NOT REPORTED IN PAPER".
This file IS the human-replicable answer key NotebookLM should reproduce.
"""

ITEMS = ['1X','3X','3Y','3Z','4Y','5X','5Y','5Z(1)','5Z(2)','5Z(3)',
         '6X','7X','7Z(1)','7Z(2)','8X','8Z(1)','8Z(2)','9X','10X','10Z']

ITEM_NAME = {
 '1X':'Peer Review','3X':'Animals: Reporting','3Y':'Animals: Technical Quality',
 '3Z':'Selection Bias: Baseline','4Y':'Sample-Size Calculation',
 '5X':'Music Intervention: Reporting','5Y':'Music Intervention: Technical Quality',
 '5Z(1)':'Selection Bias: Sequence Generation','5Z(2)':'Performance Bias: Random Housing',
 '5Z(3)':'Detection Bias: Outcome Assessment','6X':'Ethical Compliance',
 '7X':'Blinding: Reporting','7Z(1)':'Performance Bias: Experimenter Blinding',
 '7Z(2)':'Detection Bias: Assessor Blinding','8X':'Methods-Results Alignment',
 '8Z(1)':'Attrition Bias: Incomplete Data','8Z(2)':'Reporting Bias: Selective Outcomes',
 '9X':'Discussion: Limitations','10X':'Conflict-of-Interest Statement',
 '10Z':'Other Bias: Funder Influence'}

NR = "NOT REPORTED IN PAPER"
A = {}  # assessments

A['Niehues_2011_BCNEURO'] = {
 '1X':('Yes','Published in the peer-reviewed journal Basic and Clinical Neuroscience.','[p.1] "Basic and Clinical Neuroscience, Summer 2011, Volume 2, Number 4"'),
 '3X':('Yes','Species, strain, sex, age, weight, source and group size all reported.','[p.2, Methods] "A total of sixty male Wistar albino rats (Rattus norvegicus)... 3 to 5 months of age, weighing 220 to 310 g, were obtained from the animal house of the Regional University of Blumenau"'),
 '3Y':('Partly','Homogeneous animals and randomization, but no baseline behavioural comparison between groups reported.','[p.2] "They were randomized with ten rats per subgroup"'),
 '3Z':('Unclear','Animals randomized to subgroups but no arm-specific baseline data reported.','[p.2] "They were further divided into two groups: silence and music. They were randomized with ten rats per subgroup"'),
 '4Y':('No','No a priori sample-size calculation reported.',NR),
 '5X':('Yes','Genre/piece, delivery, duration, volume and control condition all specified.','[p.2, Methods] "Music (Mozart’s piano sonata, KV361, Largo, 8:35 min duration) was continuous and repeated in a compact disc player... music 65-75 dB"'),
 '5Y':('Partly','Distinct music vs control delivered, but 5 mice/cage with individuals analysed independently (pseudoreplication) and acute exposure.','[p.2] "housed in groups of five per opaque plastic cage"'),
 '5Z(1)':('Unclear','States randomized but no method of sequence generation described.','[p.2] "They were randomized with ten rats per subgroup"'),
 '5Z(2)':('Unclear','Silence and music rooms described as identical except sound – matched but still a residual room confound.','[p.2] "The silence room was exactly the same as the room in which music were played but here there was no sounds except for ambient noises"'),
 '5Z(3)':('Yes','All animals tested at a fixed timepoint after 4 weeks; no outcome-dependent selection.','[p.2] "After 4 weeks of drug treatment, the rats from each subgroup were selected for behavioral studies"'),
 '6X':('Partly','Names guideline/society compliance but no ethics-committee approval or protocol number.','[p.2] "performed in compliance with the recommendations of SBNeC (Brazilian Society of Neuroscience and Behavior), which are based on the US National Institutes of Health Guide"'),
 '7X':('No','No blinding described in any phase; observer present during testing.','[p.2] "The observer stayed in the same room, 1 m or so away from the elevated plus-maze and open-field"'),
 '7Z(1)':('Unclear','No information on whether handlers delivering music were blinded.',NR),
 '7Z(2)':('No','Observer scored behaviour live in the same room with music playing; judgment-sensitive outcome unblinded.','[p.2] "The observer stayed in the same room, 1 m or so away"'),
 '8X':('Yes','Design (2 sound x 3 doses = 6 subgroups x 10 = 60) and all EPM/OFT measures reported coherently.','[p.2] "randomized with ten rats per subgroup" + Results Figs 1-2 report all measures'),
 '8Z(1)':('Yes','60 allocated, ten per subgroup, figures show n=10 per group with no exclusions.','[Fig 1] "Bars represent the mean of groups of 10 rats"'),
 '8Z(2)':('Yes','Methods enumerate EPM and OFT measures; Results report all of them.','[p.3-5] all EPM (open/closed arm, risk assessment) and OFT (locomotion, immobility, rearing, grooming) measures reported'),
 '9X':('No','Discussion gives only future directions, no specific limitation of this study.','[p.5] "There is a need to conduct more studies, which replicate the designs used in the existing studies"'),
 '10X':('No','No conflict-of-interest / competing-interests statement present.',NR),
 '10Z':('Unclear','No funding statement; funder role cannot be assessed.',NR),
}

A['Camargo_2013_PSYN'] = {
 '1X':('Yes','Published in the peer-reviewed journal Psychology & Neuroscience.','[p.1] "Psychology & Neuroscience, 2013, 6, 3, 403 - 410"'),
 '3X':('Yes','Species, strain, sex, age, weight, source and group size all reported.','[p.404, Methods] "A total of 60 male genetically heterogeneous albino Wistar rats (Rattus norvegicus), 3 to 5 months and weighing 220 to 310 g, were obtained from the animal house of the Regional University of Blumenau"'),
 '3Y':('Partly','Homogeneous, randomized, but no baseline behavioural comparison between groups.','[p.404] "They were randomized with 10 rats per group"'),
 '3Z':('Unclear','No arm-specific baseline data reported.','[p.404] "They were randomized with 10 rats per group and orally received either simvastatin... or saline"'),
 '4Y':('No','No sample-size calculation reported.',NR),
 '5X':('Yes','Genre/piece, delivery, duration (5 h/day), schedule, volume and control all specified.','[p.404] "exposed to music for 5 h/day, between 12:00 and 5:00 PM. The music (i.e., Mozart’s piano sonata, KV361, Largo, 8:35 min duration)... 65-75 dB"'),
 '5Y':('Partly','Distinct conditions but 5 rats/cage analysed as independent (pseudoreplication).','[p.404] "housed in groups of five per opaque plastic cage"'),
 '5Z(1)':('Unclear','States randomized, no method described.','[p.404] "They were randomized with 10 rats per group"'),
 '5Z(2)':('Unclear','Silent room identical to music room but separate – residual room confound.','[p.404] "The silent room was exactly the same as the room in which music was played but no sound was made"'),
 '5Z(3)':('Yes','All animals tested at fixed timepoint after 4 weeks.','[p.404] "After 4 weeks the rats in each subgroup were selected for the behavioral studies"'),
 '6X':('Partly','Names guideline/society compliance, no committee approval/number.','[p.404] "performed in compliance with the recommendations of the Brazilian Society of Neuroscience and Behavior (SBNeC), which are based on the United States National Institutes of Health Guide"'),
 '7X':('Partly','Blinding stated for the object-recognition test only, not for the anxiety (EPM/OFT) outcomes.','[p.405] "The time spent exploring each object was recorded by an observer who was blind to treatment"'),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('No','For the anxiety outcomes the observer was present ~1 m away and unblinded.','[p.404] "The observer stayed in the same room, approximately 1 m away from the apparatus"'),
 '8X':('Yes','Methods (EPM, OFT, object recognition) and Results align; n=10/group consistent.','[p.405] "Each value reflects the mean of 10 animals per group"'),
 '8Z(1)':('Yes','60 allocated, 10/group; figures show n=10/group, no exclusions.','[Fig 1] "The data are expressed as mean ± SEM (n = 10/group)"'),
 '8Z(2)':('Yes','Methods enumerate EPM, OFT and object-recognition outcomes; Results report all.','[p.405-406] all EPM, OFT and short/long-term memory outcomes reported'),
 '9X':('Partly','Brief interpretive caveats (rat hearing range, unknown active music features) but no structured limitations.','[p.408] "unknown are the specific features of music, such as timbre, tempo, key... that are integral to its efficacy in rats"'),
 '10X':('Yes','Explicit competing-interests declaration present.','[p.409] "The authors declare that they do not have any financial or nonfinancial competing interests"'),
 '10Z':('Unclear','No funding statement; funder role cannot be assessed.',NR),
}

# Pangemanan, Chikahisa, Terzioglu filled below (already assessed in detail)
A['Pangemanan_2024_PHJ'] = {
 '1X':('Yes','Peer-reviewed Pharmacognosy Journal with review/acceptance dates.','[p.1] "Pharmacognosy Journal, Vol 16, Issue 2, Mar-Apr, 2024... Review completed: 12-02-2024; Accepted Date: 16-02-2024"'),
 '3X':('Yes','Strain, sex, source, age and weight reported; n per group in flow diagram.','[p.1-2] "Male Wistar rats sourced from Indoanilab (Bogor, Indonesia)... male rats at the age of fourteen weeks"'),
 '3Y':('Yes','Pre-CUMS baseline body weights reported per group and not significantly different.','[Table 1] "Pre CUMS ... 0.825a" (ANOVA, NS)'),
 '3Z':('Yes','Arm-specific baseline weights provided and balanced (p=0.825).','[Table 1] "Pre CUMS 163.250±12.624 ... 170.556±14.169  0.825a"'),
 '4Y':('No','No sample-size calculation; dose only based on a prior study.','[p.2] "the dose selection based on a prior study"'),
 '5X':('Partly','Genre/piece, volume, schedule, duration and control given, but speaker/delivery hardware not described.','[p.2] "Mozart music (K448) was delivered at a volume of 60-80 dB... from 6:00 pm to 6:00 am, positioned 30 cm from the cage"'),
 '5Y':('No','Music vs no-music in separate rooms; collective housing 2/cage with pups/animals not independent.','[p.2] "A separate room was designated for groups without music exposure"'),
 '5Z(1)':('Unclear','States randomized but no method described.','[p.1] "randomly assigned to two groups: control (without CUMS) and treatment"'),
 '5Z(2)':('No','Music vs control in separate rooms with no matching or counterbalancing described.','[p.2] "A separate room was designated for groups without music exposure"'),
 '5Z(3)':('No','Animals were included into the treatment group based on showing the target phenotype (low SPT).','[p.2] "criteria for inclusion involved selecting male rats... demonstrating depressive-like behavior in the treatment group as determined by the Sucrose Preference Test"'),
 '6X':('Yes','Named ethics-committee approval with a reference number.','[p.1] "received approval from the Animal Care and Use Committee of the Faculty of Veterinary Medicine, Universitas Airlangga... under reference number 2.KE.120.10.2021"'),
 '7X':('No','No blinding of any phase described.',NR),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('Unclear','No mention of assessor blinding (SPT/ELISA largely objective).',NR),
 '8X':('Partly','Internal n contradiction (text 42 vs flow diagram 39) and FST dropped, but primary SPT comparison interpretable.','[p.3] "A total of 42 rats were included in this study" vs [Fig 1] "39 rats included"'),
 '8Z(1)':('No','42 allocated but only 39 analysed; the 3 lost are unexplained.','[Fig 1] "Wistar rats (n=42)" → "39 rats included"'),
 '8Z(2)':('No','FST was measured but dropped from results "due to technical problems".','[p.2] "due to technical problems, FST cannot be analyzed"'),
 '9X':('Yes','Multiple specific limitations of this study stated.','[p.5] "This study has several limitations, such as the measurement of only the plasma corticosterone, hippocampal melatonin..."'),
 '10X':('No','No competing-interests statement located.',NR),
 '10Z':('Yes','Academic institutional support only; no commercial funder with a stake.','[p.5, Acknowledgments] "the author (LP) received support from the Faculty of Medicine, Universitas Katolik Widya Mandala Surabaya"'),
}

A['Chikahisa_2007_BBR'] = {
 '1X':('Yes','Published in Behavioural Brain Research (Elsevier), peer-reviewed.','[p.1] "Behavioural Brain Research 179 (2007) 50–59"'),
 '3X':('Yes','Strain, source, sex, age and weight reported with group sizes.','[p.2] "Mice of the Slc:ddY strain (Slc Inc., Shizuoka, Japan)... Female mice (25–32 g)... at the age of 8 weeks"'),
 '3Y':('Partly','Homogeneous and randomized to acoustic groups, but no pre-exposure baseline comparison between acoustic groups.','[p.2] "surgically treated mice were randomly assigned to one of three groups: silence... white noise... and music"'),
 '3Z':('Unclear','No arm-specific baseline data for the acoustic (music/silence/WN) groups.','[p.2] "randomly assigned to one of three groups: silence (silence group), white noise... and music"'),
 '4Y':('No','No sample-size calculation; group sizes given as "approximately n=13".','[p.2] "approximately n = 13 per group for each hormonal condition"'),
 '5X':('Yes','Genre/piece, delivery, timing, volume and two control conditions specified.','[p.2] "Music (Mozart’s piano sonata, K. 448) was played repeatedly on a CD player... sound level of the silence group was 55 dB, music 65–75 dB, and the white noise 70 dB"'),
 '5Y':('Partly','Acute exposure in a shared test room (no separate-room confound) but pseudoreplication and acute timing.','[p.2] "mice were exposed to music or white noise from 30 to 45 min before behavioral tests, and also during the tests"'),
 '5Z(1)':('Unclear','States randomly assigned, no method of sequence generation.','[p.2] "surgically treated mice were randomly assigned to one of three groups"'),
 '5Z(2)':('Unclear','All acoustic conditions run in the SAME room (no separate-room confound) but cage-position randomization not reported.','[p.2] "The silence condition was performed in the same room as the music and white-noise groups"'),
 '5Z(3)':('Yes','All animals tested once at a fixed time window; no outcome-dependent selection.','[p.2] "All behavioral testing was completed between 1300 and 1700 h, and mice were used only once for each type of behavioral test"'),
 '6X':('Yes','Named ethics committee approval with an approval number.','[p.2] "The experiments were approved by the Animal Study Committee of Tokushima University (No. 05047)"'),
 '7X':('No','No blinding described; OFT/EPM scored by automated tracking but blinding not stated.','[p.2] "recorded using an automated image analysis system (Smart System, Pan Lab s.l., Spain)"'),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('Unclear','Key OFT/EPM outcomes automated/objective, but blinding not reported and some measures manual.','[p.2] "recorded using an automated image analysis system"'),
 '8X':('Yes','Two experiments and all four behavioural tests + hormone assays reported coherently.','[p.2-6] OFT, EPM, light-dark, marble burying and hormone results all reported'),
 '8Z(1)':('Unclear','Allocation numbers given but per-group analysis n varies (9–18) without a clear reconciliation.','[Fig 1] "Sample numbers were from 9 to 18 per column"'),
 '8Z(2)':('Yes','Methods enumerate four behavioural tests and hormone measures; Results report all.','[p.3-6] all four behavioural tests and hormone levels reported'),
 '9X':('Yes','Substantive study-specific limitations discussed (mixed estrus cycle, auditory vs air-oscillation).','[p.8] "it also remains to be resolved whether an uncontrolled estrus cycle in the intact mice may have effects on these results"'),
 '10X':('No','No competing-interests statement (2007 paper, only funding acknowledgment).',NR),
 '10Z':('Yes','Government/academic grant funding; no commercial interest.','[p.8] "This work was supported by a Grant-in-Aid for Scientific Research from the 21st Century COE Program"'),
}

A['Terzioglu_2020_CMJ'] = {
 '1X':('Yes','Externally peer-reviewed (explicitly stated).','[p.5] "Peer-review: Externally peer-reviewed"'),
 '3X':('Partly','Strain and sex given and exposure window defined, but pup sex/weight and animal supplier not reported.','[p.2] "Adult female and male Wistar albino rats were housed under standard... conditions"'),
 '3Y':('Partly','Randomized to cages but no baseline comparison; perinatal litter structure (dam=unit) not addressed.','[p.2] "pregnant female rats were randomly divided into four cages"'),
 '3Z':('Unclear','No arm-specific baseline data reported between groups.','[p.2] "pregnant female rats were randomly divided into four cages"'),
 '4Y':('No','No sample-size calculation; very small n (3-4 dams/group).',NR),
 '5X':('Partly','Genre/piece/artist, volume, duration and schedule given, but delivery hardware/placement not described.','[p.2] "classical (Canon in D Major/ Johann Pachelbel, 60 dB)... listened to their own music one hour per day from GD10 to postnatal day 21"'),
 '5Y':('No','Each genre played at a different volume (60/30/120 dB) – genre confounded with loudness; one cage of dams per group (litter confound).','[p.2] "classical (... 60 dB) (n=4), traditional Sufi (... 30 dB) (n=4), and rock (... 120 dB) (n=4)"'),
 '5Z(1)':('Unclear','States randomly divided, no method described.','[p.2] "pregnant female rats were randomly divided into four cages"'),
 '5Z(2)':('No','One cage per group requiring acoustic isolation; no counterbalancing possible.','[p.2] "pregnant female rats were randomly divided into four cages; control group (no music exposure) (n=3), classical... (n=4)"'),
 '5Z(3)':('Yes','All animals subjected to the test at PND~30; no outcome-dependent selection.','[p.2] "All animals were subjected to tail suspension test"'),
 '6X':('Yes','Named ethics committee approval with date and number.','[p.2] "the local scientific Ethical Committee of Bezmialem Vakif University (Approval date:29/01/2015, Approval number: 2015/30)"'),
 '7X':('Yes','States observers were blinded to groups for the behavioural test.','[p.2] "The observers were blinded to the groups"'),
 '7Z(1)':('Unclear','No information on whether music-delivery handlers were blinded.',NR),
 '7Z(2)':('Yes','Observers scoring the judgment-sensitive TST were blinded to group.','[p.2] "The observers were blinded to the groups"'),
 '8X':('Partly','Outcomes reported but per-measure denominators vary across analyses without explanation.','[p.3] "F(3:45)=5.855" vs "F(3:38)= 9.016" (varying df across measures)'),
 '8Z(1)':('Unclear','Variable n across assays not reconciled to allocation; no clear flow.','[p.2] "Dams (n=12) and pups (n=34)" vs varying analysis df'),
 '8Z(2)':('Yes','Methods enumerate TST, ACTH/CORT/PTH and TAS/TOS/OSI; Results report all.','[p.3-4] TST, all three hormones and oxidative indices reported'),
 '9X':('Partly','One substantive but brief limitation (rat hearing/perception) stated.','[p.5] "the fact that different hearing frequency of rat results a different perception of music type than human may be an important limitation"'),
 '10X':('Yes','Explicit competing-interests declaration present.','[p.5] "Conflict of Interest: Authors declared no conflict of interest"'),
 '10Z':('Yes','University research-council grant; no commercial funder with a stake.','[p.5] "This work was supported by the Bezmialem Vakif University Research Council [grant numbers BAP-3.2015/22 and BAP-12.2016/31]"'),
}

A['Chen_2019_BIOMEDRI'] = {
 '1X':('Yes','Published in the peer-reviewed journal BioMed Research International.','[p.1] "Hindawi BioMed Research International Volume 2019, Article ID 8740674"'),
 '3X':('Yes','Strain, sex, weight, source and group sizes reported; litters identified.','[p.2] "Seventy-eight juvenile rats (42 male and 36 female, 180-220g weight)... selected from litters of six SD (Sprague Dawley) mother rats obtained from Central South University Animal Services"'),
 '3Y':('Partly','Homogeneous and randomized; no-shock groups showed equivalence but no pre-exposure baseline table.','[p.2] "Seventy-eight juvenile rats... were randomly divided into music group... and control group"'),
 '3Z':('Unclear','No arm-specific pre-exposure baseline data reported.','[p.3] "thirty juvenile rats (18 males and 12 females) were randomly divided into music group and control group"'),
 '4Y':('No','Sample sizes equal but no a priori power calculation.','[p.4] "The sample size of music and control groups is the same. The homoscedasticity was confirmed to be equal"'),
 '5X':('Yes','Genre/piece, volume, schedule, duration and control condition all specified.','[p.3] "exposed to Mozart’s piano sonata, K.488 with a sound intensity of 65-75dB... exposed to either music or ambient noise from 8 pm to 10 pm during the dark cycle for 21 consecutive days"'),
 '5Y':('Partly','Animals transported to a soundproof exposure room (reasonable), but littermates housed together and litter not modelled (pseudoreplication).','[p.3] "Pups from each group were transported to a soundproof room and exposed to either music or ambient noise"'),
 '5Z(1)':('Unclear','States randomly divided, no method described.','[p.2] "were randomly divided into music group... and control group"'),
 '5Z(2)':('Unclear','Exposure in a shared transported soundproof room; home-cage position randomization not reported.','[p.3] "transported to a soundproof room and exposed to either music or ambient noise"'),
 '5Z(3)':('Yes','All allocated animals tested at fixed ages; no outcome-dependent selection.','[p.3] "anxiety-like behaviors in all rats were examined using the elevated plus maze test (EPM) and the open field test (OFT)"'),
 '6X':('Yes','Named ethics committee approval with an approval number.','[p.2] "approved by the Animal Care and Use Committee of Central South University... (ethics approval number 201310125)"'),
 '7X':('Yes','Explicitly states all behaviour tests were blinded until data collection complete.','[p.3] "All animal behavior tests were conducted under blinded conditions, and the treatment groups were only revealed after all experimental data were obtained"'),
 '7Z(1)':('Unclear','No information on whether music-delivery handlers were blinded.',NR),
 '7Z(2)':('Yes','Behavioural outcome assessment blinded to group until data obtained.','[p.3] "All animal behavior tests were conducted under blinded conditions"'),
 '8X':('Yes','Two serials with defined n; EPM/OFT/freezing/BDNF results all align with methods.','[p.3] "thirty juvenile rats (18 males and 12 females)... Each group consisted of 9 male and 6 female"'),
 '8Z(1)':('Yes','All 78 animals accounted for across the two serials; no attrition.','[p.2-3] "Seventy-eight juvenile rats" allocated, behaviour (n=30) and BDNF (n=48) groups fully reported'),
 '8Z(2)':('Yes','Methods enumerate freezing, EPM, OFT and BDNF outcomes; Results report all, with supplementary data.','[p.9] "All profiling data are available as Supplementary Materials, Tables S1–S3"'),
 '9X':('Partly','One specific limitation acknowledged but no dedicated limitations section.','[p.7] "Whether this learned fear extinction contributes to the decrease in anxiety-like behaviors was not tested in our study"'),
 '10X':('Yes','Explicit conflict-of-interest declaration present.','[p.7] "Conflicts of Interest: The authors declare that they have no conflicts of interest"'),
 '10Z':('Yes','Government/academic grant funding; no commercial interest.','[p.7] "This research was supported by Grants from the National Natural Science Foundation of China"'),
}

A['Cheng_2024_HLYN'] = {
 '1X':('Yes','Published in Heliyon (Elsevier), peer-reviewed with submission/acceptance dates.','[p.1] "Heliyon 10 (2024) e34196... Received 8 January 2024; Received in revised form 17 June 2024; Accepted 4 July 2024"'),
 '3X':('Yes','Strain, sex, age, weight and source reported with n per group.','[p.2] "Male ICR mice aged 8 weeks, each weighing approximately 25 ± 1 g, were procured from Shanghai Slac Animal Center"'),
 '3Y':('Partly','Homogeneous and randomized to 7 groups, but no baseline behavioural comparison reported.','[p.2] "Mice were randomly divided into seven groups (n = 11)"'),
 '3Z':('Unclear','No arm-specific baseline data reported.','[p.2] "Mice were randomly divided into seven groups (n = 11)"'),
 '4Y':('No','No sample-size calculation reported.',NR),
 '5X':('Partly','Genre playlists, schedule, duration and speaker distance fully given, but sound level (dB) is never reported.','[p.2] "exposed to their respective genres of music for a duration of 2 h every evening... between 21:00 and 23:00... positioned at a distance of approximately 2 m from the mice’s enclosure"'),
 '5Y':('Partly','Delivery described and genre playlists curated, but acoustic isolation between 7 groups and group housing not detailed.','[p.2] "The sound system used for playing the music was strategically positioned at a distance of approximately 2 m from the mice’s enclosure"'),
 '5Z(1)':('Unclear','States randomly divided, no method described.','[p.2] "Mice were randomly divided into seven groups"'),
 '5Z(2)':('Unclear','Housing/cage position and acoustic isolation between groups not reported.',NR),
 '5Z(3)':('Yes','All mice tested after the last therapy; no outcome-dependent selection.','[p.2] "Open-field test, sucrose preference test and forced swimming test were performed after the last music therapy"'),
 '6X':('Yes','Named ethics committee approval with number and date.','[p.2] "approval from the Animal Ethics Committee of the Jiangxi University of Chinese Medicine (JZLLSC20230462, approval on 03/24/2023)"'),
 '7X':('No','No blinding of any phase described.',NR),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('Unclear','No mention of assessor blinding for behavioural scoring.',NR),
 '8X':('Yes','Methods (SPT, FST, OFT, ELISA, PCR, WB, IF) and Results align across all assays.','[p.2-9] all behavioural and molecular outcomes reported with figures'),
 '8Z(1)':('Unclear','Behavioural n=11 stated, but molecular subsets (N=4–6) are not reconciled to allocation.','[Fig 3] "N = 4 – 6 in each group"'),
 '8Z(2)':('Yes','Methods enumerate behavioural and molecular outcomes; Results report all.','[p.7-9] sucrose preference, immobility, corticosterone, GR, BDNF, synaptic proteins, neurogenesis all reported'),
 '9X':('Yes','Explicit, specific limitations stated.','[p.10] "there are also several limitations in our present study. Firstly, the method of music exposure... Secondly... this selection is not exhaustive"'),
 '10X':('Yes','Explicit competing-interest declaration present.','[p.12] "Declaration of competing interest: The authors declare that they have no known competing financial interests"'),
 '10Z':('Yes','Government/provincial academic funding; no commercial interest.','[p.12] "This research was funded by grants from the Science and Technology Plan Project of Jiangxi Provincial Administration of Traditional Chinese Medicine"'),
}

A['Escribano_2014_APPANBSC'] = {
 '1X':('Yes','Published in Applied Animal Behaviour Science (Elsevier), peer-reviewed.','[p.1] "Applied Animal Behaviour Science 152 (2014) 73–82"'),
 '3X':('Partly','Strain, sex, age, weight, cycle status and housing given, but the animal supplier/source is not named.','[p.74] "Female Wistar rats (200–250 g) three months old and with regular ovarian cycles were used... housed in groups of three animals in a plastic cage"'),
 '3Y':('Partly','Homogeneous, cycling females, randomized; no pre-exposure baseline comparison.','[p.74] "Control rats were randomly assigned to one of three groups: (i) silence group, (ii) white noise group and (iii) Mozart music group"'),
 '3Z':('Unclear','No arm-specific baseline data reported.','[p.74] "Control rats were randomly assigned to one of three groups... with n = 6 rats per group"'),
 '4Y':('No','No sample-size calculation reported.',NR),
 '5X':('Yes','Genre/piece, delivery, distance, timing, control conditions and measured volume all reported.','[p.74] "Music (Mozart’s 2 piano sonata, K. 448) was played repeatedly on a CD player... situated at 70–100 cm from the rats... 65 dB for music and white noise... measured by a decibelmeter"'),
 '5Y':('Partly','Same room used for all acoustic conditions (no separate-room confound) and equal dB, but 3/cage pseudoreplication and acute exposure.','[p.74] "The silence condition was maintained in the same room as the music and white noise groups"'),
 '5Z(1)':('Unclear','States randomly assigned, no method described.','[p.74] "Control rats were randomly assigned to one of three groups"'),
 '5Z(2)':('Unclear','Same room for all conditions (no separate-room confound) but cage-position randomization not reported.','[p.74] "The silence condition was maintained in the same room as the music and white noise groups"'),
 '5Z(3)':('Yes','Rats used only once per test at a fixed time window; no outcome-dependent selection.','[p.74] "All behavioural testing was completed between 13:00 and 17:00 h, and rats were used only once for each type of behavioural test"'),
 '6X':('Yes','Named ethics committee approval (with EU directive compliance).','[p.74] "The experiments were approved by the Bioethics Committee of Córdoba University and carried out according to the guidelines of the Directive of 24 November 1986 (86/609/ECC)"'),
 '7X':('No','No blinding described in any phase.',NR),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('Unclear','Behaviour video-recorded and EPM scored automatically, but assessor blinding not reported.','[p.75] "These anxiety tests were recorded digitally in a Sony Handycam DCR-DVD 105 videocamera"'),
 '8X':('Yes','Four experiments, EPM/light-dark and hormone assays reported coherently; n=6/group consistent.','[Table 1] F-values reported for all four experiments and both tests'),
 '8Z(1)':('Yes','n=6 per subgroup reported throughout (OVX n=18, SO n=18); no attrition.','[Fig 1] "n = 6 for each subgroup of treatments"'),
 '8Z(2)':('Yes','Methods enumerate EPM, light-dark and hormone outcomes; Results report all.','[Table 1] all EPM and light-dark measures reported for every experiment'),
 '9X':('No','Discussion offers mechanism and future directions but no specific limitation of this study.','[p.81] "the effect of background noise... in masking the effects of ultrasound and loud noises needs further investigation"'),
 '10X':('No','No competing-interests statement located.',NR),
 '10Z':('Unclear','No funding statement; funder role cannot be assessed.',NR),
}

A['Milbratz_2017_ALN'] = {
 '1X':('Yes','Published in Archivos Latinoamericanos de Nutrición, a peer-reviewed journal.','[p.106] "ARCHIVOS LATINOAMERICANOS DE NUTRICIÓN... Vol. 67 Nº 2, 2017"'),
 '3X':('Yes','Species, strain, sex, age, weight, source and housing all reported.','[p.107] "A total of 24 male genetically heterogeneous albino Wistar rats (Rattus norvegicus), 3 to 5 months and weighing 225 g on average (SD = 9 g), were obtained from the animal house of the Regional University of Blumenau... housed individually"'),
 '3Y':('Partly','Homogeneous animals but allocation method unstated and no baseline comparison reported.','[p.108] "The animals were divided into four groups... each comprising six animals"'),
 '3Z':('Unclear','No arm-specific baseline data or balancing procedure reported.','[p.108] "The animals were divided into four groups: control group (CG), cocoa powder group (CPG), music group (MG) and cocoa powder with music group (CPMG)"'),
 '4Y':('No','No sample-size calculation reported.',NR),
 '5X':('Yes','Genre/piece, delivery, duration, schedule, volume and control all specified.','[p.108] "exposed to classical music for 5 hours / day between 1:00 and 6:00 PM, during the 15 days... Mozart’s music (Serenade N.10... Gran partita K.361/370a, Largo... 8:35 minutes long)... music room had a sound level of 65-75 dB"'),
 '5Y':('Partly','Individually housed (no cage pseudoreplication) but music and silence delivered in separate rooms (room confound).','[p.108] "The silent room where the animals of CG and CPG groups stayed had no music and its sound level was 50 dB"'),
 '5Z(1)':('Unclear','Allocation method not described (no randomization stated).','[p.108] "The animals were divided into four groups"'),
 '5Z(2)':('No','Music vs silent rooms (separate rooms) with no matching/counterbalancing described.','[p.108] "The silent room where the animals of CG and CPG groups stayed had no music"'),
 '5Z(3)':('Yes','All animals tested on the last day; no outcome-dependent selection.','[p.108] "On the last day of intervention all animals were individually subjected to the EPM and OF tests"'),
 '6X':('Yes','Named ethics committee approval with a protocol number.','[p.107] "This study was approved by the university Ethics Committee for Animal Research (CEUA) by the protocol No. 125/14"'),
 '7X':('No','No blinding described; observer present during testing.','[p.108] "The observer stayed in the same room approximately one meter away from each apparatus"'),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('No','Observer present ~1 m away during tests; judgment-sensitive outcome unblinded.','[p.108] "The observer stayed in the same room approximately one meter away from each apparatus and recorded the tests with a video camera for later behavioral analysis"'),
 '8X':('Yes','Methods (EPM, OF, antioxidant assays) and Results align; n=6/group; null EPM still reported.','[Table 2] "number of animals per group = 6"'),
 '8Z(1)':('Yes','24 allocated, 6 per group; figures/tables report n=6 with no attrition.','[Fig 1] "All data are expressed as mean ± standard deviation (n = 6 / group)"'),
 '8Z(2)':('Yes','Methods enumerate EPM, OF and antioxidant outcomes; Results report all (including non-significant EPM).','[p.109] "No statistical differences were observed between groups in the parameters analyzed in the EPM test"'),
 '9X':('Partly','Some methodological reflection (absence of a stressor) and recommendations, but no dedicated limitations.','[p.114] "A larger dose of cocoa is recommended... More behavioral tests and also verification of antioxidant activity in structures of the central nervous system are recommended"'),
 '10X':('No','No competing-interests statement located.',NR),
 '10Z':('Unclear','No funding statement; funder role cannot be assessed.',NR),
}

A['Freitas_2020_ECNE'] = {
 '1X':('Yes','Published as a journal article in EC Neurology (open-access, peer-reviewed).','[p.12] "EC Neurology 13.1 (2021): 12-20... Received: November 13, 2020; Published: December 30, 2020"'),
 '3X':('Partly','Strain, sex, age, source, n and housing reported, but body weight is not given.','[p.13] "Thirty-two female BALB/c mice at 21st postnatal day were obtained from the animal house of the Evandro Chagas Institute"'),
 '3Y':('Partly','Homogeneous; allocation method unstated and no baseline comparison; 2x2 factorial.','[p.13] "the animals were divided in four groups: standard environment without music (IE-NM)... and environment enriched with music (EE-CM)"'),
 '3Z':('Unclear','No arm-specific baseline data reported.','[p.13] "the animals were divided in four groups"'),
 '4Y':('No','No sample-size calculation reported.',NR),
 '5X':('Yes','Genre/composers, volume, duration, schedule and control condition specified.','[p.13] "Diverse musical pieces of various classical music composers including Bach, Chopin... Mozart... reproduced around 65dB... remained for 12 hours, with a 10-minute silent interval, every 30 minutes... three times a week during the dark cycle, three months"'),
 '5Y':('Partly','8 animals per cage (pseudoreplication) and acoustic separation of music vs no-music groups not described.','[p.13] "Each enriched cage housed 8 individuals"'),
 '5Z(1)':('Unclear','Allocation method not described.','[p.13] "the animals were divided in four groups"'),
 '5Z(2)':('Unclear','Housing/acoustic separation between music and no-music groups not described.',NR),
 '5Z(3)':('Yes','All subjects tested at PND120; no outcome-dependent selection.','[p.13] "At the 120th postnatal day, all subjects were submitted to behavioral tests"'),
 '6X':('Yes','Named ethics committee approval with a number.','[p.13] "The project was approved by the Ethics Committee on the Use of Animals (CEUA/UFPA, nº 2472060218)"'),
 '7X':('No','Behaviour analysed by automated tracking but no blinding described.','[p.13] "All tests were video recorded and analyzed using the Any-Maze"'),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('Unclear','Automated (objective) tracking used, but assessor blinding not reported.','[p.14] "Images were analyzed with ANY-maze software"'),
 '8X':('Partly','Outcomes reported, but ANOVA error df (~59) is inconsistent with the stated n=32 animals.','[p.15] "F 1,59 = 8.259" (with only 32 mice allocated)'),
 '8Z(1)':('Unclear','ANOVA df implies more observations than the 32 allocated animals; denominators not reconciled.','[p.13] "Thirty-two female BALB/c mice" vs [p.15] "F 1,59"'),
 '8Z(2)':('Yes','Methods enumerate OF, EPM and Morris water maze outcomes; Results report all.','[p.15-17] open field, EPM and water-maze outcomes all reported'),
 '9X':('No','Discussion offers mechanism and comparison gaps but no specific limitation of this study.','[p.18] "Because no previous data combining enriched environment and music intervention are available we cannot compare our findings"'),
 '10X':('Yes','Explicit conflict-of-interest declaration present.','[p.18] "Conflict of Interest: All authors have no conflict of interest"'),
 '10Z':('Unclear','No funding statement; funder role cannot be assessed.',NR),
}

A['Flores_2018_NP'] = {
 '1X':('Yes','Published in Neural Plasticity (Hindawi), peer-reviewed with review dates.','[p.1] "Hindawi Neural Plasticity Volume 2018, Article ID 8205245... Received 27 April 2018; Revised 11 October 2018; Accepted 5 November 2018"'),
 '3X':('Partly','Strain, sex, age, source and n reported, but body weight not given and age is internally inconsistent (months vs weeks).','[p.2] "Seventy-three male Balb/C mice (mean age 8–10 months) were obtained from the animal facilities of the National Institute of Psychiatry"'),
 '3Y':('Partly','Homogeneous and randomized, but no baseline comparison reported.','[p.2] "animals were randomly assigned to one of the following groups"'),
 '3Z':('Unclear','No arm-specific baseline data reported.','[p.2] "animals were randomly assigned to one of the following groups"'),
 '4Y':('No','No sample-size calculation reported.',NR),
 '5X':('Yes','Delivery, distance, calibrated volume, schedule, frequency-transposition and control all reported.','[p.3] "a speaker system located 40 cm from the cage. The PAS were calibrated for an intensity of 70 ± 10 dB SPL... from 9 min/d on the first day to 90 min/d at the end of the 5 weeks... pieces from Mozart"'),
 '5Y':('Partly','Stimulus carefully transposed to the rodent hearing range and calibrated, but acoustic isolation between PAS/No-PAS groups and housing density not detailed (pseudoreplication).','[p.4] "The Mozart pieces were transposed into the hearing range of mice... shifted the frequency range from 7554 Hz to 19,485 Hz"'),
 '5Z(1)':('Unclear','States randomly assigned, no method described.','[p.2] "animals were randomly assigned to one of the following groups"'),
 '5Z(2)':('Unclear','Acoustic separation of PAS vs No-PAS groups and cage position not described.',NR),
 '5Z(3)':('Yes','All animals tested at a fixed point after housing; no outcome-dependent selection.','[p.3] "Two days after the end of ENR and PAS housing, mice were exposed to Porsolt’s forced-swim test"'),
 '6X':('Yes','Named institutional ethics committee approval with a number.','[p.2] "approved by the local Institutional Ethics Committee of the National Institute of Psychiatry... (IACUC: CEI/02/06/20/09)"'),
 '7X':('Yes','Behavioural analysis and histology both explicitly blinded to group.','[p.3] "The behavior of the animals was video recorded and analyzed blind to the experimental group with the ANY-maze behavioral tracking software"'),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('Yes','Outcome assessment (behaviour and histology) blinded to group.','[p.5] "All samples were number coded, and the researcher conducting the analyses was blinded to the experimental groups"'),
 '8X':('Partly','Outcomes align with methods, but subject age is internally contradictory (8-10 months in Methods vs 8-10 weeks in figures).','[p.2] "mean age 8–10 months" vs [Fig 1] "8-10 weeks old"'),
 '8Z(1)':('Yes','73 allocated; experiment groups sum to 73 with per-group n reported; histology subsample (n=5) stated.','[p.2] "Seventy-three male Balb/C mice"; groups reported as n=5 and n=7–8'),
 '8Z(2)':('Yes','Methods enumerate FST, DCX and Arc outcomes; Results report all (corticosterone reported as non-significant).','[p.5] "we found that corticosterone levels did not vary among the groups tested"'),
 '9X':('Partly','Several substantive caveats about what the study cannot explain, mixed with future-directions.','[p.11] "our study cannot explain the beneficial effects of PAS in ENR mice... by increased levels of BDNF nor by increased levels of DCX neurons"'),
 '10X':('Yes','Explicit conflict-of-interest declaration present.','[p.11] "Conflicts of Interest: The authors have no conflicts of interest to declare"'),
 '10Z':('Yes','Government/academic (INPRFM, CONACYT) funding; no commercial interest.','[p.11] "This work was financially supported through the budget of INPRFM... financed by CONACYT (Grant Infraestructura 2015/254773)"'),
}

A['Fu_2023_TRANSPSY'] = {
 '1X':('Yes','Published in Translational Psychiatry (Nature), peer-reviewed with review dates.','[p.1] "Translational Psychiatry (2023) 13:317... Received: 22 March 2023 Revised: 14 September 2023 Accepted: 20 September 2023"'),
 '3X':('Yes','Strain, sex, age, weight and source reported; mice housed individually.','[p.1] "Male C57BL/6 mice (7 weeks old, 22 ± 1.5 g) were purchased from Fang Yuanyuan Breeding Farm (Beijing, China)"'),
 '3Y':('Partly','Homogeneous but allocation method unstated, group sizes very unequal (6/10/6/14), and no baseline comparison.','[p.2] "We divided the mice into four groups, control (n = 6), CUMS (n = 10), Music (n = 6), and CUMS +Music (n = 14)"'),
 '3Z':('Unclear','No arm-specific baseline data reported.','[p.2] "We divided the mice into four groups, control (n = 6), CUMS (n = 10), Music (n = 6), and CUMS +Music (n = 14)"'),
 '4Y':('No','No sample-size calculation; group sizes unequal and unjustified.',NR),
 '5X':('Partly','Genre playlist with frequencies, schedule, duration, distance and control given, but sound level (dB) not reported.','[p.2] "CUMS+Music mice listened to music for 1.5 h each night from 20:30 to 22:00. The music player was located approximately 2 m away... 25 musical pieces (detailed music frequency see Table 1)"'),
 '5Y':('Partly','Mice individually housed (no cage pseudoreplication), but acoustic isolation of music vs non-music groups not described.','[p.2] "Mice were housed individually and exposed to three different stressors daily"'),
 '5Z(1)':('Unclear','Allocation method not described.','[p.2] "We divided the mice into four groups"'),
 '5Z(2)':('Unclear','Individually housed; acoustic separation of music/non-music groups and cage position not described.',NR),
 '5Z(3)':('Yes','All mice tested at a fixed point after 28 days; no outcome-dependent selection.','[p.2] "The second day after the mice were treated with CUMS and/or music for 28 days, they were subjected to behavioral tests"'),
 '6X':('Yes','Named ethics committee approval.','[p.2] "approved by the Animal Care and Use Committee of Minzu University of China"'),
 '7X':('Yes','Outcome assessors explicitly blinded to treatment for all behavioural tests.','[p.2] "The tests were performed by an individual who was blinded to the treatment status of the animals"'),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('Yes','Behavioural outcome assessment blinded to group.','[p.2] "the number of entries into the open and closed arms... were recorded by an observer blinded to the animal groups"'),
 '8X':('Yes','Methods (OFT, TST, SPT, NSF, EPM and molecular) and Results align.','[p.2] all five behavioural tests described and reported'),
 '8Z(1)':('Yes','Group allocation explicitly stated (6/10/6/14) and analysed; no attrition reported.','[p.2] "control (n = 6), CUMS (n = 10), Music (n = 6), and CUMS +Music (n = 14)"'),
 '8Z(2)':('Yes','Methods enumerate the behavioural and molecular outcomes; Results report all.','[Abstract] "open field, tail suspension, sucrose preference, novelty suppressed feeding, and elevated plus maze tests"'),
 '9X':('Yes','Explicit, specific limitations stated.','[Discussion] "there are some limitations in this study. The first limitation of this study is that we used only male mice"'),
 '10X':('Yes','Explicit competing-interests declaration present.','[Declarations] "COMPETING INTERESTS The authors declare no competing interests"'),
 '10Z':('Yes','Government/academic funding (NSFC, Ministry of Education); no commercial interest.','[Acknowledgements] "This study was supported by the National Natural Science Foundation of China (82071676)"'),
}

A['Fu_2025_TRANSPSY'] = {
 '1X':('Yes','Published in Translational Psychiatry (Nature), peer-reviewed.','[p.1] "Translational Psychiatry... The Author(s) 2025... Music therapy as a preventive intervention for postpartum depression"'),
 '3X':('Yes','Strain, sex, age, weight and source reported with group sizes.','[p.2] "Female BALB/c mice, aged 11 weeks and weighing 22 ± 1.5 g, were acquired from the Fang Yuanyuan Breeding Farm"'),
 '3Y':('Partly','Homogeneous with balanced n=10/group, but allocation described as "arbitrary" and no baseline comparison.','[p.2] "The mice were arbitrarily divided into four groups, each containing ten mice"'),
 '3Z':('Unclear','No arm-specific baseline data reported.','[p.2] "systematically allocated into four distinct groups, each consisting of ten individuals"'),
 '4Y':('No','No sample-size calculation reported.',NR),
 '5X':('Yes','Genre playlist, delivery (sealed room), volume, duration, schedule and control all specified.','[p.2] "listened to music prepared by us for 2 h per day, with a music volume of approximately 70 decibels... placed in a sealed room"'),
 '5Y':('Partly','Music delivered in a sealed room (room confound) but handling controlled by moving control groups an equal distance.','[p.2] "the mice were placed in a sealed room... we also moved the control groups an equal distance, despite them not needing to listen to the music"'),
 '5Z(1)':('Unclear','Allocation described as arbitrary, no random method stated.','[p.2] "The mice were arbitrarily divided into four groups"'),
 '5Z(2)':('Unclear','Sealed exposure room used with movement controlled, but home-cage position randomization not described.','[p.2] "the mice were placed in a sealed room"'),
 '5Z(3)':('Yes','All mice tested at a fixed point after the model phase; no outcome-dependent selection.','[p.2] "Two days after the final E2 injection, the mice were subjected to a comprehensive set of behavioral assessments"'),
 '6X':('Yes','Named ethics committee endorsement.','[Ethics] "receiving full endorsement from the Animal Care and Use Committee at Minzu University of China"'),
 '7X':('Yes','All behavioural tests explicitly conducted blind to treatment.','[p.2] "All tests were conducted blindly to maintain the integrity of the data"'),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('Yes','Outcome assessors unaware of treatment groups.','[p.2] "An observer, unaware of the animals’ treatment groups, accurately recorded the number of entries and the time spent in each arm"'),
 '8X':('Yes','Methods (SPT, OFT, TST, NSF, EPM, FST and molecular) and Results align; balanced n=10/group.','[p.2] all behavioural tests described with n=10/group'),
 '8Z(1)':('Yes','40 allocated (4x10); analysed with no attrition reported.','[p.2] "each containing ten mice"'),
 '8Z(2)':('Yes','Methods enumerate behavioural and molecular outcomes; Results report all (incl. FST).','[p.2] sucrose preference, open field, tail suspension, novelty-suppressed feeding, EPM and forced swimming tests all described'),
 '9X':('Yes','Explicit, specific limitations stated.','[Discussion] "this study has several limitations. The first limitation is that PPD mice only simulate human postpartum depression patients"'),
 '10X':('Yes','Explicit competing-interests declaration present.','[Declarations] "COMPETING INTERESTS The authors declare no competing interests"'),
 '10Z':('Yes','Government/academic funding (NSFC, Guangdong Provincial Fund); no commercial interest.','[Acknowledgements] "This study was supported by the National Natural Science Foundation of China (82471560) and the Guangdong Provincial Fund"'),
}

A['Krishnamurthy_2025_INDIANJTRADITKNOW'] = {
 '1X':('Yes','Published in the Indian Journal of Traditional Knowledge, peer-reviewed.','[p.319] "Indian Journal of Traditional Knowledge Vol 24(4), April 2025... Received 30 August 2024; revised 16 February 2025; accepted 03 April 2025"'),
 '3X':('Partly','Strain, sex, age and n given, but body weight and animal supplier not reported.','[p.320] "Adult male Wistar rats (2 months old) were obtained and housed in polypropylene cages"'),
 '3Y':('Partly','Homogeneous and randomized, but no baseline behavioural comparison reported.','[p.320] "The animals were randomly assigned to four groups"'),
 '3Z':('Unclear','No arm-specific baseline data reported.','[p.320] "The animals were randomly assigned to four groups... Control group... (n=8); Stress group... (n=8)"'),
 '4Y':('No','No sample-size calculation reported.',NR),
 '5X':('Yes','Genre/raga/instrument, delivery, distance, measured volume, duration and schedule all specified.','[p.320] "placed 1 meter away from the speaker in a sound attenuated room... average sound level of 65-75 dB (checked with a sound level meter) for 1 h for a period of 21 days... Raga Mohana on Veena"'),
 '5Y':('Partly','Sound-attenuated exposure room (reasonable) but separate from controls and housing density not detailed.','[p.320] "The animals were placed 1 meter away from the speaker in a sound attenuated room"'),
 '5Z(1)':('Unclear','States randomly assigned, no method described.','[p.320] "The animals were randomly assigned to four groups"'),
 '5Z(2)':('Unclear','Music delivered in a separate sound-attenuated room; cage-position randomization not described.','[p.320] "placed 1 meter away from the speaker in a sound attenuated room"'),
 '5Z(3)':('Yes','All animals tested post-treatment; no outcome-dependent selection.','[p.319] "Post-treatment, the animals were subjected to an elevated plus maze, sucrose preference test, forced swim test, novel object recognition test, and T-maze"'),
 '6X':('Yes','Named ethics committee approval with an approval number.','[p.327] "approval (07/BVR/2022) was granted for the usage of animals" by "the Institutional Animal Ethics Committee, KLE College of Pharmacy"'),
 '7X':('Partly','Blinding via coded videos mentioned but with limited detail.','[p.321] "The videos recorded during the behavioural experiments were coded to avoid bias"'),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('Yes','Behavioural videos coded (masked) before analysis to avoid bias.','[p.321] "The videos recorded during the behavioural experiments were coded to avoid bias"'),
 '8X':('Yes','Methods (EPM, SPT, FST, NORT, T-maze) and Results align; ANOVA df (3,28) consistent with n=8/group.','[p.321] "F3,28=11.90" (4 groups x 8 = 32)'),
 '8Z(1)':('Yes','n=8 per group (4x8=32); figures and ANOVA df consistent; no attrition.','[Fig 2] "NC: Normal control (n=8); CUMS... (8)"'),
 '8Z(2)':('Yes','Methods enumerate five behavioural tasks; Results report all.','[p.321-325] EPM, SPT, FST, NORT and T-maze outcomes all reported'),
 '9X':('Partly','Acknowledges the study measured only behaviour (no mechanistic markers), but framed largely as future work.','[p.326] "There are some limitations of the present study... Further studies include, estimation of cortisol levels, neurotransmitter levels, BDNF, cytokine profiling and histological studies"'),
 '10X':('Yes','Explicit competing-interests declaration present.','[p.327] "Conflict of Interest: The authors declare that they have no competing interests"'),
 '10Z':('Yes','Academic institutional support only; no commercial funder with a stake.','[p.327] "Funding: KLE College of Pharmacy, KAHER, and Bengaluru for infrastructure and other support"'),
}

A['Ren_2024_ASEAN'] = {
 '1X':('Yes','Published as a journal article in ASEAN Journal of Psychiatry (open-access).','[p.1] "ASEAN Journal of Psychiatry, Vol. 25 (8) October, 2024; 1-14"'),
 '3X':('Partly','Strain, sex and age reported, but body weight and animal supplier not given.','[Methods] "Wild-type C57BL/6 male mice (8 weeks old) were used"'),
 '3Y':('Partly','Litter/age/sex-matched and identical chambers, but no baseline behavioural comparison reported.','[p.1] "mice were litter-matched, age-matched and sex-matched in all animal trials"'),
 '3Z':('Yes','Animals were litter-, age- and sex-matched across groups (an explicit balancing procedure).','[p.1] "mice were litter-matched, age-matched and sex-matched in all animal trials"'),
 '4Y':('No','No sample-size calculation reported.',NR),
 '5X':('Partly','Genre, delivery distance, daily duration and schedule given, but sound level (dB) and specific tracks not reported.','[p.1] "three distinct chronic sound stresses from 9 am to 12 pm and from 2 pm to 5 pm... The voice box is stuck to the top of the box about 0.25 m from the mice"'),
 '5Y':('Partly','Identical chambers per group (some environmental matching), but volume not reported and possible cage-level pseudoreplication.','[p.1] "Each of them was placed in identical chambers with similar treatments except that three groups were put under three distinct chronic sound stresses"'),
 '5Z(1)':('Unclear','Group allocation method not described (matching mentioned, but not random sequence generation).','[p.1] "There were four groups of mice, with ten mice per group"'),
 '5Z(2)':('Unclear','Identical chambers used per group, but cage-position randomization/counterbalancing not described.','[p.1] "Each of them was placed in identical chambers with similar treatments"'),
 '5Z(3)':('Yes','All mice tested daily during exposure; no outcome-dependent selection.','[p.1] "Every day, at around 1 pm, each mouse is weighed and the Sucrose Preference Test... are conducted"'),
 '6X':('Partly','States adherence to laboratory animal care but no ethics-committee approval reported.','[Declarations] "The care and use of laboratory animals were conducted in a[ccordance with guidelines]"'),
 '7X':('No','No blinding described in any phase.',NR),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('Unclear','No mention of assessor blinding for the behavioural outcomes.',NR),
 '8X':('Yes','Methods (SPT, NB, OFT, EPM, TST, FST and molecular) and Results align.','[p.1] six behavioural tests described and evaluated'),
 '8Z(1)':('Yes','Four groups of ten mice stated; no attrition reported.','[p.1] "There were four groups of mice, with ten mice per group"'),
 '8Z(2)':('Yes','Methods enumerate six behavioural tests plus molecular markers; Results report them.','[p.1] "Sucrose Preference Test (SPT), the Nest Building (NB), the Open Field Test (OFT), the Elevated Plus Maze (EPM), the Tail Suspension Test (TST) and the Forced Swim Test (FST)"'),
 '9X':('Yes','Explicit, specific limitations stated.','[Discussion] "This study has several limitations. The first limitation was the time frame. One week of acoustic stimuli might not be enough"'),
 '10X':('Yes','Explicit conflict-of-interest declaration present.','[Declarations] "Conflict of Interest Statement: The authors declare that they have no conflict of interest"'),
 '10Z':('Unclear','No funding statement located; funder role cannot be assessed.',NR),
}

A['Saghari_2021_BIOINTERFACE'] = {
 '1X':('Yes','Published in Biointerface Research in Applied Chemistry, peer-reviewed with review dates.','[p.1] "Volume 11, Issue 1, 2021, 7775 - 7784... Received: 4.06.2020; Revised: 1.07.2020; Accepted: 1.07.2020"'),
 '3X':('Partly','Strain, sex, weight and n given, but animal age not reported.','[p.2] "Fifty-six healthy male Wistar rats (200–250 gr) were used to develop an animal model of PTSD"'),
 '3Y':('Partly','Homogeneous and randomized, but no baseline behavioural comparison reported.','[p.2] "Rats were randomly divided into four main groups (14 rats for each group)"'),
 '3Z':('Unclear','No arm-specific baseline data reported.','[p.2] "Rats were randomly divided into four main groups... control, PTSD, music (mu), PTSD+Music"'),
 '4Y':('No','No sample-size calculation reported.',NR),
 '5X':('Partly','Genre/piece, duration and schedule given, but sound level (dB) and delivery hardware not reported.','[p.2] "Rats in music groups were exposed to 12 h daily Mozart’s piano sonata K.448 music for seven days, starting from 7:00 to 17:00"'),
 '5Y':('Partly','Distinct music vs control but delivery setup and acoustic isolation not described; housing density unstated.','[p.2] "Rats in music groups were exposed to 12 h daily Mozart’s piano sonata K.448 music for seven days"'),
 '5Z(1)':('Unclear','States randomly divided, no method described.','[p.2] "Rats were randomly divided into four main groups"'),
 '5Z(2)':('Unclear','Housing/cage position and acoustic isolation of music vs control not described.',NR),
 '5Z(3)':('Yes','All rats tested after a pre-specified delay; pre-specified subgroup assignment for the two test batteries.','[p.2] "Seven days after PTSD, rats were again brought to the laboratory and were undergone all behavioral tests"'),
 '6X':('Yes','Named research-center ethics approval with an ethics code.','[p.2] "This study was approved by the Kerman Neuroscience Research Center (Ethics code: 97-23)"'),
 '7X':('No','Automated video tracking used but no blinding of any phase described.','[p.2] "their behavior was recorded for 5 min with Ethovision video-tracking system"'),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('Unclear','Outcomes captured by automated tracking (objective), but assessor blinding not reported.','[p.3] "Behavioral data for MWM was collected using Ethovision automation software"'),
 '8X':('Yes','Methods (open field, Morris water maze, passive avoidance) and Results align; n=56, 14/group.','[p.2] "Fifty-six... rats... four main groups (14 rats for each group)... two subgroups: seven rats for Open field and Morris water maze tests and seven rats for Shuttle box"'),
 '8Z(1)':('Yes','56 allocated, 14/group with pre-specified 7+7 subgroups; no attrition reported.','[p.2] "14 rats for each group... seven rats for Open field and Morris water maze tests and seven rats for Shuttle box test"'),
 '8Z(2)':('Yes','Methods enumerate OFT, MWM and passive-avoidance outcomes; Results report all.','[p.2-3] open field, Morris water maze and passive avoidance tests described and reported'),
 '9X':('No','No study-specific limitations discussed.',NR),
 '10X':('Yes','Explicit conflict-of-interest declaration present.','[p.7782] "Conflicts of Interest: The authors declare no conflict of interest"'),
 '10Z':('Yes','Academic research-center grant funding; no commercial interest.','[Funding] "This research was funded by the Kerman Neuroscience Research Center (Grant No: KNRC/EC/97-23)"'),
}

A['Li_2010_BR'] = {
 '1X':('Yes','Published in Brain Research (Elsevier), peer-reviewed.','[p.71] "BRAIN RESEARCH 1347 (2010) 71–79... Accepted 25 May 2010"'),
 '3X':('Partly','Strain (transgenic C57BL/6J background), sex, age and breeding given, but body weight not reported.','[Methods] "Adult wild-type and littermate BDNF Met/Met male mice (2–3 months old) derived from heterozygous BDNF +/Met x BDNF+/Met crossed parents were used"'),
 '3Y':('Partly','Age-matched littermate pairs used, but no baseline behavioural comparison reported.','[Methods] "To reduce experimental variability, age-matched littermate pairs resulting from heterozygous crossings were used"'),
 '3Z':('Yes','Age-matched littermate pairs were used (a litter-balancing procedure).','[Methods] "age-matched littermate pairs resulting from heterozygous crossings were used"'),
 '4Y':('No','No sample-size calculation reported.',NR),
 '5X':('Partly','Genre, delivery, control conditions and measured volume given, but the exposure duration/schedule is not clearly reported.','[Methods] "the sound level of the control group was ~40 dB... white noise 50–60 dB... and music 50–60 dB (was played on a CD player)"'),
 '5Y':('Partly','Music and white noise matched in dB, but acoustic isolation/housing density not detailed (litter-based pseudoreplication).','[Methods] "music 50–60 dB (was played on a CD player)"'),
 '5Z(1)':('Unclear','States randomly assigned, no method described.','[Methods] "mice were randomly assigned to three groups: control group, white noise group and music group"'),
 '5Z(2)':('Unclear','Housing/cage position and acoustic isolation not described.',NR),
 '5Z(3)':('Yes','All animals underwent behavioural measurement; no outcome-dependent selection.','[Methods] "Adult... mice... were used for all experiments. All behavioral measurements were performed"'),
 '6X':('Yes','Named ethics committee approval.','[Methods] "approved by the Animal Care and Use Committee of the School of Medicine of Shandong University"'),
 '7X':('Yes','States behavioural raters were blinded (to genotype).','[Methods] "All behavioral measurements were performed by raters blind to genotype"'),
 '7Z(1)':('Unclear','No information on handler/delivery blinding to the acoustic condition.',NR),
 '7Z(2)':('Unclear','Raters were blind to genotype, but blinding to the music/white-noise condition is not stated.','[Methods] "All behavioral measurements were performed by raters blind to genotype"'),
 '8X':('Yes','Methods (open field, EPM, BDNF ELISA) and Results align across genotypes.','[Results] open field and elevated plus maze and BDNF outcomes reported by genotype and sound condition'),
 '8Z(1)':('Unclear','Per-group n varies (6–9) without a clear allocation/analysis reconciliation.','[Fig] "n = 6–9"'),
 '8Z(2)':('Yes','Methods enumerate behavioural and BDNF outcomes; Results report all.','[Results] open field, EPM and PFC/amygdala/hippocampus BDNF all reported'),
 '9X':('No','No study-specific limitations discussed.',NR),
 '10X':('No','No conflict-of-interest / competing-interests statement located.',NR),
 '10Z':('Unclear','No funding statement located; funder role cannot be assessed.',NR),
}

A['Papadakakis_2019_BBR'] = {
 '1X':('Yes','Published in Behavioural Brain Research (Elsevier), peer-reviewed.','[p.1] "Behav. Brain Res. 372 (2019) 112023"'),
 '3X':('Partly','Strain, sex, housing, n and developmental ages reported, but body weight and supplier not given.','[Methods] "Male Sprague–Dawley rats... litters were culled to 8–10 pups (60–70% male subjects)... maternal separation group (MS, n = 22) and control group (CG, n = 20)"'),
 '3Y':('Partly','Homogeneous and randomized, but no baseline behavioural comparison reported.','[Methods] "On PND 2, rats were randomly divided into two groups: maternal separation group (MS, n = 22) and control group (CG, n = 20)"'),
 '3Z':('Unclear','No arm-specific baseline data reported.','[Methods] "rats were... randomly divided into two groups"'),
 '4Y':('No','No sample-size calculation reported.',NR),
 '5X':('Yes','Genre/piece, duration, schedule, volume and control condition all specified.','[Methods] "exposed from PND 21 to PND 76 for 12 h/day to Mozart K. 448... The intensity of Mozart music stimulus was 65–75 dB, while the intensity of ambient noise was 65 dB"'),
 '5Y':('Partly','Music vs a separate silence room (room confound) and litter-based pseudoreplication.','[Methods] "silence room with ambient noise. The intensity of Mozart music stimulus was 65–75 dB"'),
 '5Z(1)':('Unclear','States randomly divided, no method described.','[Methods] "rats were randomly divided into two groups"'),
 '5Z(2)':('No','Music delivered vs a separate silence room with no matching/counterbalancing described.','[Methods] "silence room with ambient noise"'),
 '5Z(3)':('Yes','All animals tested at a fixed age; no outcome-dependent selection.','[Methods] "At approximately three months of age, elevated plus maze procedure, forced swim test and social approach task were applied"'),
 '6X':('Partly','Names directive/guideline compliance but no ethics-committee approval reported.','[Methods] "Experiments were conducted in accordance with the European Communities Council Directive (86/609/EEC) and the National Institutes of Health Guide"'),
 '7X':('No','No blinding described in any phase.',NR),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('Unclear','No mention of assessor blinding.',NR),
 '8X':('Yes','Methods (EPM, FST, social approach, Golgi spine density) and Results align.','[Methods] "the animals were submitted individually to the social approach task (SAT), elevated plus maze (EPM) test"'),
 '8Z(1)':('Yes','Allocation stated (MS n=22, CG n=20) with the 2x2 music design; no unexplained attrition.','[Methods] "maternal separation group (MS, n = 22) and control group (CG, n = 20)"'),
 '8Z(2)':('Yes','Methods enumerate behavioural and spine-density outcomes; Results report all.','[Results] EPM, FST, social approach and dendritic spine outcomes all reported'),
 '9X':('Yes','Explicit, specific limitations stated.','[Discussion] "a number of important limitations need to be considered. First, the specific effect of music versus other types of auditory stimuli was not investigated"'),
 '10X':('No','No competing-interests statement located.',NR),
 '10Z':('Yes','Academic departmental support; no commercial funder with a stake.','[Acknowledgement] "This study was supported by the Department of Psychology and the Department of Biology of the University of Crete"'),
}

A['Rizzolo_2021_CC'] = {
 '1X':('Yes','Published in Cerebral Cortex (Oxford University Press), peer-reviewed.','[p.1] "Cerebral Cortex, January 2021;31: 620–634... Original Article"'),
 '3X':('Yes','Strain, sex, supplier, housing, age and body-weight context and group sizes all reported.','[Methods] "Male Wistar rats from Janvier Labs were paired housed in standard cages... initiated at middle age in rats (15 months old)"'),
 '3Y':('Partly','Groups balanced on body weight, but no baseline behavioural comparison reported.','[Methods] "Based on their body weight at 14 months of age, the 33 rats were pseudo-randomly affected to music (M) or white noise (WN) condition"'),
 '3Z':('Yes','Allocation was balanced on body weight (an explicit balancing procedure).','[Methods] "Based on their body weight at 14 months of age, the 33 rats were pseudo-randomly affected to music (M) or white noise (WN) condition"'),
 '4Y':('No','No sample-size calculation reported.',NR),
 '5X':('Yes','Genre, delivery, distance, volume, duration and schedule and control all specified.','[Methods] "chronic (6 h/day, 3 times/week) and long-lasting (4–8 months) music exposure... an acoustic baffle adjusted to 70 dB was placed 1 m from the cages... classical music (M) or white noise (WN)"'),
 '5Y':('Partly','Careful matched-dB delivery with an acoustic baffle, but paired housing introduces mild pseudoreplication.','[Methods] "an acoustic baffle adjusted to 70 dB was placed 1 m from the cages, which ensures a correct auditory perception"'),
 '5Z(1)':('Yes','Allocation described as a stratified (body-weight-balanced) pseudo-random assignment.','[Methods] "the 33 rats were pseudo-randomly affected to music (M) or white noise (WN) condition"'),
 '5Z(2)':('Unclear','Cage-position randomization/counterbalancing not described.',NR),
 '5Z(3)':('Yes','All surviving animals assessed at pre-specified ages; dropout was natural aging mortality.','[Methods] "Only rats that were still alive at the end of the longitudinal follow up (23 months) were considered for all behavioral and biochemical [analyses]"'),
 '6X':('Partly','Names EU directive compliance but no ethics-committee approval reported.','[Methods] "Experiments were carried out in accordance with the European Communities Council Directive (2010/63/UE)"'),
 '7X':('Yes','States the experimenter was blinded to the acoustic condition.','[Methods] "The experimenter was blind to the nature of auditory exposure of groups of rats"'),
 '7Z(1)':('Yes','Experimenter blinded to the music/white-noise condition.','[Methods] "The experimenter was blind to the nature of auditory exposure of groups of rats"'),
 '7Z(2)':('Yes','Outcome assessor blinded to the acoustic condition.','[Methods] "The experimenter was blind to the nature of auditory exposure of groups of rats"'),
 '8X':('Yes','Methods (working/spatial memory, EPM, locomotor, circadian) and Results align.','[Methods] "Wistar rats were exposed (6 h/day, 3 times a week) to either classical music (M) or white noise (WN). A set of behavioral tests"'),
 '8Z(1)':('Yes','Numbers reported (33 allocated, 27 survivors) with the reason being natural aging mortality.','[Methods] "n = 33... followed up until 23 months old (23 months, n = 27)"'),
 '8Z(2)':('Yes','Methods enumerate behavioural/biochemical outcomes; Results report all.','[Results] working and spatial reference memory, locomotor activity and circadian outcomes reported'),
 '9X':('Yes','Dedicated limitations section discussing study-design constraints.','[Discussion] "Limitations Inherent to the Study Design... animal studies on music related effects are difficult to compare"'),
 '10X':('Yes','Explicit conflict-of-interest declaration present.','[Declaration] "no financial, personal, or other relationships with concerned people or organizations"'),
 '10Z':('Yes','Regional government/academic funding; no commercial interest.','[Funding] "Normandy Regional Council (REVIMUSIC Research Grant and PhD Fellowship of Lou Rizzolo); Agence Regional pour la Sante"'),
}

A['Sampaio_2017_PSYNEURO'] = {
 '1X':('Yes','Published in Psychology & Neuroscience (APA), peer-reviewed.','[p.1] "Effect of Music Therapy on the Developing Central Nervous System of Rats... Psychology & Neuroscience, June 2017, DOI: 10.1037/pne0000087"'),
 '3X':('Partly','Strain, sex and n given, but body weight, supplier and housing details not reported.','[Methods] "Male (n = 10) and female (n = 10) Wistar rats were used in the present study"'),
 '3Y':('Partly','Homogeneous, but allocation method unstated and no baseline behavioural comparison.','[Methods] "Male (n = 10) and female (n = 10) Wistar rats were used"'),
 '3Z':('Unclear','No arm-specific baseline data reported.',NR),
 '4Y':('No','No sample-size calculation reported.',NR),
 '5X':('Partly','Genre/piece, volume, duration and schedule given, but the control condition and delivery hardware are not clearly described.','[Methods] "Mozart’s Sonata for Two Pianos was played at a sound intensity of 65 dB for 4 hours per day, 2 hours in the morning and 2 hours in the afternoon"'),
 '5Y':('Partly','Within-subject developmental design with limited technical detail on acoustic delivery/isolation.','[Methods] "Mozart’s Sonata for Two Pianos was played at a sound intensity of 65 dB for 4 hours per day"'),
 '5Z(1)':('Unclear','Allocation method to music/control not described.',NR),
 '5Z(2)':('Unclear','Housing/cage position and acoustic isolation not described.',NR),
 '5Z(3)':('Yes','Animals tested at fixed developmental ages (1, 2, 3, 4 months); no outcome-dependent selection.','[Methods] "The procedures were performed when animals were approximately 1 month of age, and repeated once they completed 2, 3, [and 4 months]"'),
 '6X':('Yes','Named ethics committee approval with a protocol number.','[Methods] "complied with the criteria established by the Ethics Committee on Animal Use (Comitê de Ética no Uso Animal–CEUA) of UnB under protocol no. 80243"'),
 '7X':('No','No blinding described in any phase.',NR),
 '7Z(1)':('Unclear','No information on handler/delivery blinding.',NR),
 '7Z(2)':('Unclear','No mention of assessor blinding.',NR),
 '8X':('Yes','Methods (EPM, open field across ages) and Results align.','[Methods] tests conducted at 1, 2, 3 and 4 months with EPM and open field reported'),
 '8Z(1)':('Yes','Group sizes reported (n=10 male, n=10 female); no attrition reported.','[Methods] "Male (n = 10) and female (n = 10) Wistar rats were used"'),
 '8Z(2)':('Yes','Methods enumerate the behavioural outcomes; Results report them across ages.','[Results] elevated plus maze and open field outcomes reported across developmental ages'),
 '9X':('No','No study-specific limitations discussed.',NR),
 '10X':('No','No competing-interests statement located.',NR),
 '10Z':('Unclear','No funding statement located; funder role cannot be assessed.',NR),
}

if __name__ == '__main__':
    print("Studies assessed so far:", len(A))
    for s in A:
        miss=[i for i in ITEMS if i not in A[s]]
        print(f"  {s}: {len(A[s])}/20" + (f"  MISSING {miss}" if miss else ""))
