project:
  type: book
  output-dir: ../docs
  resources:
    - cossee_logo.png
    - cover.png

book:
  title: "Music exposure reduces anxiety- and depression-like behavior in rodents: a systematic review and multilevel meta-analysis"
  subtitle: "Online supplementary (reproducible workflow + full outputs)"


  # Adds top bar + links
  navbar:
    logo: cossee_logo.png
    logo-alt: "COSSEE logo"
    pinned: true
    right:
      - icon: github
        aria-label: GitHub
      - text: "OSF"
        href: https://osf.io/mv78t                   # change if needed
      - text: "Paper"
        href: https://doi.org/XXXXX                  # optional

  # Adds left sidebar controls + search box
  sidebar:
    style: "floating"
    search: true
    collapse-level: 2

  chapters:
    - index.qmd
    - effect_size_calculation.qmd
    - overall_effect.qmd
    - uni_moderators.qmd
    - publication_bias.qmd
    - crime_q.qmd
    - leave_one_out.qmd
    - main_figures.qmd
    - Alluvial.qmd


number-sections: false
bibliography: references.bib
biblio-style: apalike

format:
  html:
    theme:
      - cosmo
      - styles.scss
    mainfont: "Inter, Aptos, Segoe UI, Helvetica Neue, Arial, sans-serif"
    fontsize: 1.03em
    linestretch: 1.45
    favicon: cossee_logo.png

    toc: true
    toc-depth: 3
    toc-location: left
    fig-cap-location: bottom
    tbl-cap-location: top

    code-tools: true
    code-copy: true
    

    link-external-newwindow: true
    smooth-scroll: true

    # nicer citations in browser
    citeproc: true
    page-layout: full
    grid:
      sidebar-width: 240px
      body-width: 1600px
      margin-width: 24px
      gutter-width: 0.75rem
execute:
  freeze: auto
  warning: false
  message: false

editor: visual
