---
title: "overall_effect_lnVR"
---

```{r}
#| label: setup
#| include: false
pacman::p_load(
               DT,
               dtplyr,
               here, 
               knitr,
               tidyverse,
               patchwork,
               metafor,
               orchaRd
               )

#| label: load_and_clean_data
# LOAD THE lnVR DATASET HERE
db <- readr::read_csv(here("..","data","db_lnVR.csv")) %>%
  mutate(across(c(C_n, Ex_n, C_mean, Ex_mean, C_SE, Ex_SE, C_SD, Ex_SD, lnVR, lnVR_var), as.numeric)) %>%
  mutate(across(where(is.character), as.factor)) 


# CALCULATE VCV USING lnVR VARIANCE
VCV <- metafor::vcalc(
  vi = lnVR_var,       
  cluster = Cohort_ID, # The clustering variable (Study_ID + Ex_ID)
  obs = ES_ID,         # The unique observation/effect size ID
  rho = 0.5,           # Assumed correlation between outcomes from the same cohort
  data = db 
)

```

```{r}
#| label: model_outcome_type

mOV <- rma.mv(yi = lnVR, 
                  V = VCV, 
              mods = ~ 1,
                  random = list(~1 | Study_ID,
                                ~1 | ES_ID,
                                ~1 | Strain),
                  test = "t",
                  method = "REML", 
                  sparse = TRUE,
                  data = db)

summary(mOV)
```


```{r}
#| label: i2_extraction
orchaRd::i2_ml(mOV)
```


```{r}
r2OV <- round(r2_ml(mOV), 4)
r2OV
```




```{r}
#| label: orchard_overall
#| fig-width: 6
#| fig-height: 4
#| warning: false
orchard_overall<-orchard_plot(mOV,
               group = "Study_ID",
               xlab = "lnVR", 
              flip = FALSE) +
            scale_colour_brewer(palette = "Set1") +
            scale_fill_brewer(palette = "Dark2")+scale_y_continuous(limits = c(-6,11),breaks = seq(-6, 10, by = 2),
                                                                    minor_breaks = seq(-6, 11, by = 1 ))
orchard_overall
```
```{r}
#| label: save-figure
#| eval: false

ggsave(filename = here("..","Plots", "overall_lnVR.pdf"),
       plot = orchard_overall,
       dpi = 300, device = cairo_pdf)

ggsave(filename = here("..","Plots", "overall_lnVR.jpg"),
       plot = orchard_overall,
       width = 7,  
       height = 9,  
       dpi = 300)

```








